name: Lint

on:
  push:
    branches:
      - "**"
      - "!main"
      - "!master"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        id: rustc_install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Check
        run: |
          cargo check
      - name: Formatting
        run: |
          cargo fmt --all -- --check
      - name: Clippy
        run: |
          cargo clippy
      - name: Assert no files have changed
        run: |
          git status
          ! [[ $(git status -s) ]]
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        id: rustc_install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Test
        run: |
          cargo test